version: '3.7'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: rw-swagger-ui
    environment:
      - API_URL=http://localhost:1314/openapi.json
    ports:
      - "7777:8080"

  database:
    image: mysql:5.7
    container_name: rw-database
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql:/var/lib/mysql
