swagger: "2.0"
info:
  title: Real World Example App
  description: Real World Example App
  version: ""
host: localhost:1313
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /ping:
    get:
      tags:
      - ping
      summary: health_check ping
      description: health_check
      operationId: ping#health_check
      responses:
        "200":
          description: OK response.
      schemes:
      - http
